accounts/urls.py
from django.urls import path, include

from . import views

app_name = 'accounts'

urlpatterns = [
	path('signup/', views.signup_view, name = 'signup'),
	path('login/', views.login_view, name = 'login'),
	path('logout/', views.logout_view, name = 'logout'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('trackexpense.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, view=never_cache(serve))

trackexpense/urls.py
from django.urls import path


from . import views

app_name = 'expenses'

urlpatterns = [
	path('', views.index, name = 'dashboard'),
	path('addexpense/', views.NewExpense, name = 'create'),
	path('labels/',views.CategoryView, name = 'labels'),
	path('labels/add', views.NewCategory, name = 'addlabel'),
	path('labels/<str:title>', views.LabelView, name = 'labelview'),
]

accounts/models.py
from django.db import models

# Create your models here.

trackexpense/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
	title = models.CharField(max_length = 50)
	author = models.ForeignKey(User,on_delete = models.CASCADE)
	def __str__(self):
		return self.title

class Expense(models.Model):
	title = models.CharField(max_length = 50)
	pub_date = models.DateTimeField(auto_now_add= True)
	author = models.ForeignKey(User,default=None,on_delete=models.CASCADE)
	amount = models.IntegerField()
	desc = models.CharField(max_length = 200, verbose_name='Description')
	category = models.ForeignKey(Category, default=None, on_delete = models.CASCADE, null=True,blank=True)
	def __str__(self):
		return self.title
	
class Bill(models.Model):
	title = models.CharField(max_length = 50)
	due_date = models.DateTimeField(auto_now_add= True)
	author = models.ForeignKey(User,default=None,on_delete=models.CASCADE)
	amount = models.IntegerField()
	desc = models.CharField(max_length = 200, verbose_name='Description')
	category = models.ForeignKey(Category, default=None, on_delete = models.CASCADE, null=True,blank=True)
	def __str__(self):
		return self.title

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=254, required=True)
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

trackexpense/forms.py
from django import forms
from . import models

class NewExpense(forms.ModelForm):
	class Meta:
		model = models.Expense
		fields = ['title','amount','desc', 'category']

class NewCategory(forms.ModelForm):
	class Meta:
		model = models.Category
		fields = ['title'] 

accounts/views.py
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import generic
from django.template import loader
from django.contrib.auth.decorators import login_required

from . import forms


# Create your views here.
def signup_view(request):
	if request.user.is_authenticated:
		return redirect('expenses:dashboard')
	else:
		if request.method == 'POST':
			form = forms.SignUpForm(request.POST)
			if form.is_valid():
				user = form.save()
				login(request, user)
				return redirect('expenses:dashboard')
		else:
			form = forms.SignUpForm()
		return render(request,'accounts/signup.html',{'form': form})


def login_view(request):
	if request.user.is_authenticated:
		return redirect('expenses:dashboard')
	else:
		if request.method == 'POST':
			form = AuthenticationForm(data = request.POST)
			if form.is_valid():
				user = form.get_user()
				login(request, user)
				if 'next' in request.POST:
					return redirect(request.POST.get('next'))
				else:
					return redirect('expenses:dashboard')
		else:
			form = AuthenticationForm()
		return render(request, 'accounts/login.html',{'form' : form})

def logout_view(request):
	if request.method == 'POST':
		logout(request)
		return redirect('accounts:login')

@login_required(login_url = "/accounts/login")
def profile(request):
	userr = request.user

trackexpense/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth.decorators import login_required
from datetime import datetime
# Create your views here.
from .models import Expense, Category
from . import forms


@login_required(login_url = "/accounts/login")
def index(request):
	userr = request.user
	expenses_list = Expense.objects.filter(author = userr).filter(pub_date__lte= datetime.now()).order_by('-pub_date')
	return render(request,'main/index.html',{'expenses_list': expenses_list})

@login_required(login_url = "/accounts/login")
def CategoryView(request):
	category_list = Category.objects.filter(author = request.user).order_by('title')
	return render(request, 'main/Category.html',{'category_list': category_list})
	
@login_required(login_url = "/accounts/login")
def NewExpense(request):
	if request.method == 'POST':
		form = forms.NewExpense(request.POST)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.author = request.user
			instance.save()
			return redirect('expenses:dashboard')
	else:
		form = forms.NewExpense()
	return render(request,'main/NewExpense.html', {'form':form})

@login_required(login_url = "/accounts/login")
def NewCategory(request):
	if request.method == 'POST':
		form = forms.NewCategory(request.POST)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.author = request.user
			instance.save()
			return redirect('expenses:dashboard')
	else:
		form = forms.NewCategory()
	return render(request,'main/NewCategory.html', {'form':form})

@login_required(login_url = "/accounts/login")
def LabelView(request, title):
	userr = request.user
	expenses_list = Expense.objects.filter(author=userr, category__title = title, pub_date__lte= datetime.now(), ).order_by('-pub_date')
	return render(request,'main/index.html',{'expenses_list': expenses_list})
	

templates/accounts/base.html
<html>
	<head>
		{% block head %}
		{% endblock head %}	
	
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src=""></script>
		{% block cssfile %}
		{% endblock cssfile %}
		</head>

		<body>
			{% block content %}
			{% endblock content %}
		</body>
</html>

templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load static %}
{% include 'accounts/Homepage.svg' %}

{% block head %}
<title>Log In</title>
{% endblock head %}

{% block cssfile %}
<link rel = "stylesheet" type = "text/css" href = "{% static 'accounts/login.css' %}">
{% endblock cssfile %}

{% block content %}
  <div class = "head">
    <h1>Cashify</h1>
    <small>Make financial planning easier</small>
  </div>
  <div id="formdiv" class="d-flex flex-row p-2">
  <form class = "site-form" action = "{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        <strong>{{ field.label_tag }}</strong><br>
        {{ field }}<br>
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% if field.errors %}
          <p style="color: red">{{ field.errors}}</p>
        {% endif %}
      </p>
    {% endfor %}
    {% if request.GET.next %}
      <input type = "hidden" name = "next" value = "{{ request.GET.next }}">
    {% endif %}
      <button type="submit">Log In</button>
      <p id="signuplink">Don't have an account?<a href =" {% url 'accounts:signup' %}">Sign Up here!</a></p>

  </form>
</div>
{% endblock content %}

templates/accounts/signup.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block head %}
<title>Sign Up</title>
{% endblock head %}

{% block cssfile %}
<link rel = "stylesheet" type = "text/css" href = "{% static 'accounts/signup.css' %}">
{% endblock cssfile %}

{% block content %}
  <div class = "head">
    <h1>Sign up</h1>
  </div>
  <form class = "site-form" action = "{% url 'accounts:signup' %}" method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        <strong>{{ field.label_tag }}</strong><br>
        {{ field }}<br>
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock content %}

templates/main/Category.html
{% extends 'main/base.html' %}
{% load static %}
{% block head %}
	{% if user.is_authenticated %}
		<title>My Dashboard</title>
	{% else %}
		<script type = "text/javascript">
		window.location = "{% url 'login' %}"
		</script>
	{% endif %}
{% endblock head %}
{% block css %}

<link rel="stylesheet" type="text/css" href="{% static 'main/Category.css' %}">

{% endblock css %}
{% block content %}
	<div class = "main">
		<div class = "jumbotron text-center">
			<h1>Your Labels</h1>
		</div>
		<div class = "main-body">
		<div class = "label-display">
		{% if category_list %}
			{% for category in category_list %}	
				<ul>
					<li><a href = "{% url 'expenses:labelview' title=category %}">{{ category }}</a></li>
				</ul>
			
			{% endfor %}
		{% else %}
			<p>No labels have been added yet.</p>
		{% endif %}
		</div>
		<a class = "btn btn-success"  href = "{% url 'expenses:addlabel' %} " role = "button">Add New Label</a>
	</div>
	</div>
{% endblock content %}

templates/main/NewCategory.html
{% extends 'main/base.html' %}
{% load static %}
{% block head %}
<title>Add New Category</title>
{% endblock head %}

{% block css %}
<link rel = "stylesheet" type = "text/css" href = "{% static 'main/NewExpense.css' %}">
{% endblock css %}

{% block content %}
<body>
 <div class = "jumbotron">
	<h1>Add New Label</h1>
</div>
<form class = "site-form" action = "{% url 'expenses:addlabel' %}" method = "POST">
	{% csrf_token %}
	{% for field in form %}
      <div class = "form-group">
        <strong>{{ field.label_tag }}</strong>
        {{ field }}
      </div>
    {% endfor %}
	<input class = "btn btn-success" type = "submit" value = "Add New Label">
</form>
</body>
{% endblock content %}

templates/main/NewExpense.html
{% extends 'main/base.html' %}
{% load static %}
{% block head %}
<title>Add New Expense</title>
{% endblock head %}

{% block css %}
<link rel = "stylesheet" type = "text/css" href = "{% static 'main/NewExpense.css' %}">
{% endblock css %}

{% block content %}
<body>
<div class = "jumbotron">
  <h1>Add new expense</h1>
</div>
<form class = "site-form" action = "{% url 'expenses:create' %}" method = "POST">
	{% csrf_token %}
  {% for field in form %}
  <div class = "form-group">
        <strong>{{ field.label_tag }}</strong><br>
        {{ field }}<br>
  </div>
    {% endfor %}
	<input class = "btn btn-success " type = "submit" value = "Add New Expense">
</form>
</body>
{% endblock content %}

templates/main/base.html
{% load static %}
<html>
<head>
	{% block head %}
	<title>My Project</title>
	{% endblock head %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="{% static 'main/base.js' %}"></script>
	<link rel = "stylesheet" type = "text/css" href = "{% static 'main/base.css' %}">

	{% block css %}
	{% endblock css %}
</head>
<body>
	<div id="sidebar">
			<div class="toggle-btn" onclick = "toggleSidebar()">
				<span class = "bar1"></span>
				<span class = "bar2"></span>
				<span class = "bar3"></span>

			</div>
			
			<nav>

					
				<ul>
					<li>Hi {{ request.user.username }}!</li>
					<li><a href = "{% url 'expenses:dashboard' %}">Home</a></li>
					<li><a href = "{% url 'expenses:create' %}">Add New Expense</a></li>
					<li><a href = "{% url 'expenses:labels' %}">Labels</a></li>
					<li>
						<form class = "logout-link" action = "{% url 'accounts:logout' %}" method = "POST">
							{% csrf_token %}
							<button type = "submit">Logout</button>
						</form>
					</li>

				</ul>
			</nav>
		</div>
<div id = 'mainbody'>
	{% block content %}
	{% endblock content %}
</div>
</body>
</html>

templates/main/details.html
{% extends 'main/base.html' %}
{% load static %}
{% block head %}
	{% if user.is_authenticated %}
		<title>My Dashboard</title>
	{% else %}
		<script type = "text/javascript">
		window.location = "{% url 'login' %}"
		</script>
	{% endif %}
{% endblock head %}
{% block css %}

<link rel="stylesheet" type="text/css" href="{% static 'main/index.css' %}">

{% endblock css %}
{% block content %}
<p>You are viewing the details of {{ expense.title }} expense</p>
{% endblock content %}

templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}
{% block head %}
	{% if user.is_authenticated %}
		<title>My Dashboard</title>
	{% else %}
		<script type = "text/javascript">
		window.location = "{% url 'login' %}"
		</script>
	{% endif %}
{% endblock head %}
{% block css %}

<link rel="stylesheet" type="text/css" href="{% static 'main/index.css' %}">

{% endblock css %}
{% block content %}
	<div class = "main">
		<div class = "jumbotron text-center">
			<h1>Your Dashboard</h1>
		</div>

		{% if expenses_list %}
			<table class = "table table-striped table-hover ">
				<tr>
					<th>Title</th>
					<th>Amount</th>
					<th>Date</th>
					<th>Label</th>
				</tr>
			{% for expense in expenses_list %}
				<tr>
					<td><a href="">{{ expense.title }}</a></td>
					<td id = {% if expense.amount > 0 %} "positive" {% else %} "negative" {% endif %}>{{expense.amount|stringformat:"+d"}}</td>
					<td>{{ expense.date.date }}</td>
					<td>{{ expense.category }}</td>
				</tr>
			{% endfor %}
			</table>

		{% else %}
			<p>No expenses have been added yet.</p>
		{% endif %}
	</div>
{% endblock content %}